CREATE OR REPLACE VIEW usgs.public_assembly AS
(SELECT a.ogc_fid,
    a.geom,
    a.permanent_identifier,
    a.source_featureid,
    a.source_datasetid,
    a.source_datadesc,
    a.source_originator,
    a.data_security,
    a.distribution_policy,
    a.loaddate,
    a.fcode,
    a.name,
    a.islandmark,
    a.pointlocationtype,
    a.admintype,
    a.addressbuildingname,
    a.address,
    a.city,
    a.state,
    a.zipcode,
    a.gnis_id,
    a.foot_id,
    a.complex_id,
    a.globalid,
    b.name AS fcode_name
   FROM usgs.structures a
     JOIN usgs.fcode_choices b ON a.fcode = b.id
  WHERE b.name::text = ANY (ARRAY[
    'Amusement / Water Park'::character varying,
    'Auditorium / Concert Hall / Theater / Opera House'::character varying,
    'Convention Center'::character varying,
    'Community / Recreation Center'::character varying,
    'Fair / Exhibition / Rodeo Grounds'::character varying,
    'House of Worship'::character varying,
    'Institutional Residence / Dorm / Barracks'::character varying,
    'Outdoor Theater / Amphitheater'::character varying,
    'Public Attraction or Landmark Building'::character varying,
    'Racetrack / Dragstrip'::character varying,
    'Shopping Mall / Complex'::character varying,
    'Sports Arena / Stadium'::character varying,
    'Zoo'::character varying]::text[]));